"""add unique constraint on ticker date

Revision ID: b2a6be1381ab
Revises: 2828439440cc
Create Date: 2026-10-06 16:15:39.002603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a6be1381ab'
down_revision: Union[str, Sequence[str], None] = '2828439440cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_ticker_date', 'ohlcv', ['ticker', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ticker_date', 'ohlcv', type_='unique')
    # ### end Alembic commands ###
